service: lambda-orchestrator

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    SERVICE_TOKEN: ${env:SERVICE_TOKEN}
    CUSTOMERS_API_URL: ${env:CUSTOMERS_API_URL}
    ORDERS_API_URL: ${env:ORDERS_API_URL}

functions:
  createAndConfirmOrder:
    handler: src/handlers/createAndConfirmOrder.handler
    events:
      - http:
          path: orchestrator/create-and-confirm-order
          method: post

  health:
    handler: src/handlers/health.handler
    events:
      - http:
          path: orchestrator/health
          method: get

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
